version: '3.2'
services:
  mysql:
    build: ./mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
#      - ./system:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    networks:
      databse-network:


  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - '8060:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      databse-network:


networks:
  databse-network:
    driver: bridge